### ISSUE TITLE
Request to join beta

### ISSUE THREAD

**Issue by agnelnieves** [adobe-private/react-spectrum-v3#419]
# 📝 Feedback

Been following spectrum since the css library was launched. Love the components

## 🔦 Context

Just an enthusiast who enjoys getting involved in different projects

## 💻 Code Sample
--

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Spectrum CSS   | 2.18.0
| Browser          | chrome 80.0.3987.149
| Operating System | macOS Catalina 10.15.4 Beta

## 🧢 Your Company/Team

Ultimate Software

**Comment by matthewdeutsch** [comment]
Hi @agnelnieves, nice to meet you! I'm the Product Manager for React Spectrum. You can officially sign up for the beta here: https://experiencecloudpanel.adobe.com/c/a/6ZhhcgAPawOKV5dT84suYd. 

Looking forward to your feedback! Feel free to reach out to me at deutsch (at) adobe.com if you have any questions.

-Matt

**Comment by agnelnieves** [comment]
Awesome, will sign up. Thanks for the reply @matthewdeutsch!
