### ISSUE TITLE
Way to autoFocus non-tabbable element in a FocusScope

### ISSUE THREAD

**Issue by Andarist** [adobe-private/react-spectrum-v3#595]
# 🙋 Feature Request

It would be great to have a way to use autoFocus in combination with non-tabbable (but focusable) element

## 🤔 Expected Behavior

Allow for autofocusing element with `tabIndex={-1}`

## 😯 Current Behavior

Only tabbable elements can be autoFocused now:
https://github.com/adobe-private/react-spectrum-https://github.com/adobe-private/react-spectrum-v3/blob/d126789d5fac8d7196c30ab4e0507efc05e1380f/packages/%40react-aria/focus/src/FocusScope.tsx#L302-L303

## 💁 Possible Solution

As `tabIndex={-1}` elements are not included in tab sequence and there might be many arbitrary elements with `tabIndex={-1}` set on them I don't believe having a way to autoFocus "first" of those would be a good solution.

What I was thinking is to provide a specialized wrapper component - something like `<AutoFocus/>` that could register the intention of focusing a particular element (or rather - first within that subtree?). A good thing about such a solution would be the ability to autoFocus arbitrary element which also might be sometimes desirable and it would be possible to customize it with `tabbables` prop - so it could only include tabbables or all focusables within it.

I'm not sure yet about the exact API of such `<AutoFocus/>` - there are definitely few ways you could go with this:
- rendering sentinels like for the FocusScope itself
- cloneElement
- use a hook instead of a component that would accept a ref within which the search should be performed
- possibly something else

I would happily help you implement this if only we can agree that this would be a nice addition and we figure out the dream API for this.

## 🔦 Context

Sometimes it is advisable to autofocus such elements, according to https://w3c.github.io/aria-practices/#keyboard-interaction-7 :
- "Unless a condition where doing otherwise is advisable, focus is initially set on the first focusable element." (and this might not be first tabbable)
- "If content is large enough that focusing the first interactive element could cause the beginning of content to scroll out of view, it is advisable to add tabindex=-1 to a static element at the top of the dialog, such as the dialog title or first paragraph, and initially focus that element."

## 🧢 Your Company/Team

External, non-Adobe 😉

**Comment by devongovett** [comment]
This seems like a reasonable feature. We generally support `autoFocus` as a prop on many components, so to auto focus a specific element you could use that prop directly on the element you want of focus. But to auto focus the first "focusable" as opposed to "tabbable" element within a scope seems useful.

Perhaps we could have the `autoFocus` prop accept a value like `autoFocus="focusable"` or `autoFocus="tabbable"`? Maybe not the greatest API though...

> What I was thinking is to provide a specialized wrapper component - something like `<AutoFocus/>`

This would be fairly easy to build using `useFocusManager`:

```tsx
function AutoFocus({children, tabbable}) {
  let focusManager = useFocusManager();
  useEffect(() => {
    // focuses the first element if none already focused
    // perhaps we can also add `focusFirst` and `focusLast` methods
    focusManager.focusNext({tabbable});
  }, []);

  return children;
}

<FocusScope>
  <AutoFocus>
    {/* children */}
  </AutoFocus>
</FocusScope>
```

What do you think?

**Comment by Andarist** [comment]
> We generally support autoFocus as a prop on many components, so to auto focus a specific element you could use that prop directly on the element you want of focus.

I guess this makes a lot of sense. It's actually super easy to implement a helper hook for this. My initial thoughts were that using a component-based API would be simpler to use as it maybe wouldn't require creating a ref to an element manually, OTOH such API would be more magical in its implementation so maybe I have just overthought this as a simple hooks API is a way to go?

> Perhaps we could have the autoFocus prop accept a value like autoFocus="focusable" or autoFocus="tabbable"? Maybe not the greatest API though...

This was one of the possibilities that I was thinking about but later concluded that maybe focusing a focusable should just require a more targeted approach at all times as those cases are way less common.

> This would be fairly easy to build using useFocusManager:

If this `AutoFocus` should target the whole `FocusScope` - yes, this seems nifty. Wrapping just a part of a subtree would require some more effort, but maybe this use case is too convoluted to include it in the core library anyway?

**Comment by devongovett** [comment]
> as a simple hooks API is a way to go?

We have the `useFocusable` hook to handle this for most of our components that support being focused. It supports autoFocus along with passing through focus and keyboard events, and tabIndex.

https://github.com/adobe-private/react-spectrum-v3/blob/6c487fd9af6955d0e042daa1cf867764beb41e0e/packages/%40react-aria/focus/src/useFocusable.ts#L22

> Wrapping just a part of a subtree would require some more effort

`FocusScope` can be nested, so you could nest the part you wanted to auto focus in another scope. That could make sense to auto focus an unknown child element, but if it's a specific known element then I guess using the `autoFocus` prop through `useFocusable` or a ref with a `focus()` call would be easy enough.

**Comment by Andarist** [comment]
> This would be fairly easy to build using useFocusManager

If I understand correctly this wouldn't "scope" the autofocus to its children and actually it would be hard to achieve this without introducing an additional DOM element.

Anyway - after some additional thinking, I came to the conclusion that using `useFocusable` is totally fine. A little bit verbose, but at least robust & flexible.

Feel free to close this issue if you want.

**Comment by devongovett** [comment]
Cool. Thanks for the considerations. We can always re-open if this comes up again.
