### ISSUE TITLE
Change generated IDs prefix

### ISSUE THREAD

**Issue by Andarist** [adobe-private/react-spectrum-v3#665]
Currently generated IDs have `react-spectrum-` prefix:
https://github.com/adobe-private/react-spectrum-v3/blob/12ea682ddfbd43dbd2cc5c9c41cae77986d539b5/packages/%40react-aria/utils/src/useId.ts#L23
but when using just `@react-aria` part this doesn't prefix makes less sense (in my opinion of course) than using `react-aria-` or similar. I understand that `@react-aria` is still sort of a member of React Spectrum family, so if you don't agree with me please just close this issue. It's just nitpicking.

**Comment by devongovett** [comment]
Good catch, thanks. Should be fixed by #666.
