### ISSUE TITLE
Request to join beta

### ISSUE THREAD

**Issue by Jensen95** [adobe-private/react-spectrum-v3#698]
# 📝 Feedback

I watched [Design system and accessibility - Devon Govett aka @devongovett at @ReactEurope 2020](https://www.youtube.com/watch?v=dxDcBB7Xoxs) and found it very interesting.

## 🔦 Context

I mostly just wanted to try out the aria stuff, but spectrum also looks nice and I just want to toy with it in some small hobby projects. I tried signing up with on the link from #419 but it didn't work anymore.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Firefox/Chrome
| Operating System | MacOS/Windows 10

## 🧢 Your Company/Team

No  company inc

**Comment by snowystinger** [comment]
Hi @Jensen95, we're actually out of beta now, woohoo! You can see the published packages here https://www.npmjs.com/search?q=%40react-spectrum
We're working on an ease of use combined package, that should come along in the next couple weeks.
